name: Deploy to XAMPP

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted
    environment: local

    steps:
      - name: powershell allow...
        shell: cmd
        run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"

      - name: check powershell version
        run: $host.Version

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy directory
        run: |
          xcopy /E /I "${{ github.workspace }}" "${{ env.DESTINATION_PATH }}"
