name: Deploy to XAMPP

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: powershell allow...
        shell: cmd
        run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"

      - name: check powershell version
        run: $host.Version

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move directory
        run: |
          move "${{ env.SOURCE_PATH }}" "${{ env.DEST_PATH }}"
